/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-04-27 14:41:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.main.webapp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class updatePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	body {\r\n");
      out.write("	  font-family: Arial, sans-serif;\r\n");
      out.write("	  background-color: #f0f0f0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	h3 {\r\n");
      out.write("	  text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	label {\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	  margin-top: 10px;\r\n");
      out.write("	  width: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=text], input[type=date], input[type=email], textarea {\r\n");
      out.write("	  width: 100%;\r\n");
      out.write("	  padding: 4px;\r\n");
      out.write("	  border: 1px solid #ccc;\r\n");
      out.write("	  border-radius: 4px;\r\n");
      out.write("	  box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=radio] {\r\n");
      out.write("	  margin-right: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=submit] {\r\n");
      out.write("	  background-color: #4CAF50;\r\n");
      out.write("	  color: white;\r\n");
      out.write("	  padding: 12px 20px;\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  border-radius: 4px;\r\n");
      out.write("	  cursor: pointer;\r\n");
      out.write("	  float: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=submit]:hover {\r\n");
      out.write("	  background-color: #45a049;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.update-button {\r\n");
      out.write("	  display: flex;\r\n");
      out.write("	  justify-content: center;\r\n");
      out.write("	  align-items: center;\r\n");
      out.write("	  margin-top: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	form {\r\n");
      out.write("	  width: 60%;\r\n");
      out.write("	  margin: 0 auto;\r\n");
      out.write("	  background-color: white;\r\n");
      out.write("	  padding: 20px;\r\n");
      out.write("	  border-radius: 5px;\r\n");
      out.write("	  box-shadow: 0px 0px 5px #aaa;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>FORM DATABASE</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");


    String s_id = request.getParameter("u");

	ResultSet rs = null;
	Connection con = null;
	PreparedStatement ps = null;
	
	Class.forName("com.mysql.cj.jdbc.Driver");
	con = DriverManager.getConnection("jdbc:mysql://localhost:3306/std_data", "root", "qwer123#");
	String selectQuery = "SELECT * FROM register WHERE Email_Id = ?";
	ps = con.prepareStatement(selectQuery);
	ps.setString(1, s_id);
	rs = ps.executeQuery();
	
	if (rs.next()) {
	    
      out.write("\r\n");
      out.write("	    <div class=\"form-wrapper\">\r\n");
      out.write("	    <h3 align='center'>Edit Registration Details</h3> \r\n");
      out.write("	    <form action=\"editData.jsp\" method=\"post\" >\r\n");
      out.write("	    \r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"f_name\">First Name:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"f_name\" name=\"f_name\" value=\"");
      out.print( rs.getString("f_name") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"l_name\">Last Name:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"l_name\" name=\"l_name\" value=\"");
      out.print( rs.getString("l_name") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"DOB\">DOB:</label>\r\n");
      out.write("	        <input type=\"date\" id=\"DOB\" name=\"DOB\" value=\"");
      out.print( rs.getDate("DOB") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"email_id\">Email-Id:</label>\r\n");
      out.write("	        <input type=\"hidden\" id=\"email_id\" name=\"email_id\" value=\"");
      out.print( rs.getString("email_id") );
      out.write("\" readonly><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"mob_no\">Mob-No:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"mob_no\" name=\"mob_no\" value=\"");
      out.print( rs.getString("mob_no") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"address\">Address:</label>\r\n");
      out.write("	        <textarea id=\"address\" name=\"address\">");
      out.print( rs.getString("address") );
      out.write("</textarea><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"city\">City:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"city\" name=\"city\" value=\"");
      out.print( rs.getString("city") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"pincode\">Pin Code:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"pincode\" name=\"pincode\" value=\"");
      out.print( rs.getString("Pincode") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"state\">State:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"state\" name=\"state\" value=\"");
      out.print( rs.getString("state") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"country\">Country:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"country\" name=\"country\" value=\"");
      out.print( rs.getString("country") );
      out.write("\"><br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"gender\">Gender:</label>\r\n");
      out.write("	        <input type=\"radio\" id=\"male\" name=\"gender\" value=\"Male\" ");
      out.print( rs.getString("gender").equals("Male") ? "checked" : "" );
      out.write(">\r\n");
      out.write("	        <label for=\"male\">Male</label>\r\n");
      out.write("	        <input type=\"radio\" id=\"female\" name=\"gender\" value=\"Female\" ");
      out.print( rs.getString("gender").equals("Female") ? "checked" : "" );
      out.write(">\r\n");
      out.write("	        <label for=\"female\">Female</label><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"x_board\">Xth Board:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"x_board\" name=\"x_board\" value=\"");
      out.print( rs.getString("xth_board") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"x_per\">Xth Percentage:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"x_per\" name=\"x_per\" value=\"");
      out.print( rs.getString("xth_per") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"x_yop\">Xth Year Of Pass:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"x_yop\" name=\"x_yop\" value=\"");
      out.print( rs.getString("xth_yop") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"xii_board\">XIIth Board:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"xii_board\" name=\"xii_board\" value=\"");
      out.print( rs.getString("xiith_board") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"xii_per\">XIIth Percentage:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"xii_per\" name=\"xii_per\" value=\"");
      out.print( rs.getString("xiith_per") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"xii_yop\">XIIth Year Of Pass:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"xii_yop\" name=\"xii_yop\" value=\"");
      out.print( rs.getString("xiith_yop") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"b_tech_institute\">B_Tech_Institute:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"b_tech_institute\" name=\"b_tech_institute\" value=\"");
      out.print( rs.getString("b_tech_institute") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"b_tech_per\">B.Tech Percentage :</label>\r\n");
      out.write("	        <input type=\"text\" id=\"b_tech_per\" name=\"b_tech_per\" value=\"");
      out.print( rs.getString("b_tech_per") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"b_tech_yop\">B.Tech Year Of Pass:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"b_tech_yop\" name=\"b_tech_yop\" value=\"");
      out.print( rs.getString("b_tech_yop") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"hobby\">Hobbies:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"hobby\" name=\"hobby\" value=\"");
      out.print( rs.getString("hobbies") );
      out.write("\"><br>\r\n");
      out.write("	        \r\n");
      out.write("	        <label for=\"course\">Course:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"course\" name=\"course\" value=\"");
      out.print( rs.getString("course") );
      out.write("\"><br>\r\n");
      out.write("				\r\n");
      out.write("			<div class=\"update-button\">\r\n");
      out.write("	            <input type=\"submit\" value=\"Update\">\r\n");
      out.write("	        </div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("	   </form>       \r\n");
      out.write("	   </div>\r\n");
 
    }else{
        out.print("<div style='text-align:center;'><h1 style='color:red;'>Data Not Found</h1></div>");
}

rs.close();
ps.close();
con.close();


      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
